#!/bin/sh

BUILDTYPE=Release
if [ $# -ne 0 ]; then
  BUILDTYPE=$1
fi

#CC=clang CXX=clang++  cmake ../ -GNinja -DCMAKE_BUILD_TYPE=$BUILDTYPE -DLLVM_USE_SANITIZER=Undefined -DLLVM_BUILD_LLVM_DYLIB=ON -DLLVM_ENABLE_LIBEDIT=OFF -DLLVM_ENABLE_LIBXML2=OFF -DLLVM_ENABLE_TERMINFO=OFF -DLLVM_TARGETS_TO_BUILD="ARM;AArch64" -DCMAKE_EXE_LINKER_FLAGS="-static-libgcc -static-libstdc++" -DCMAKE_SHARED_LINKER_FLAGS="-fuse-ld=lld -static-libgcc -static-libstdc++"
CC=clang CXX=clang++  cmake ../ -GNinja -DCMAKE_BUILD_TYPE=$BUILDTYPE -DLLVM_BUILD_LLVM_DYLIB=ON -DLLVM_ENABLE_LIBEDIT=OFF -DLLVM_ENABLE_LIBXML2=OFF -DLLVM_ENABLE_TERMINFO=OFF -DLLVM_TARGETS_TO_BUILD="ARM;AArch64" -DCMAKE_EXE_LINKER_FLAGS="-static-libgcc -static-libstdc++" -DCMAKE_SHARED_LINKER_FLAGS="-fuse-ld=lld -static-libgcc -static-libstdc++"
#CC=clang CXX=clang++  cmake ../ -GNinja -DCMAKE_BUILD_TYPE=$BUILDTYPE -DLLVM_ENABLE_PROJECTS="compiler-rt;clang" -DLLVM_BUILD_LLVM_DYLIB=ON -DLLVM_ENABLE_LIBEDIT=OFF -DLLVM_ENABLE_LIBXML2=OFF -DLLVM_ENABLE_TERMINFO=OFF -DLLVM_TARGETS_TO_BUILD="ARM;AArch64" -DCMAKE_EXE_LINKER_FLAGS="-static-libgcc -static-libstdc++" -DCMAKE_SHARED_LINKER_FLAGS="-fuse-ld=lld -static-libgcc -static-libstdc++"
